[general]
import = [
    "~/.config/alacritty/themes/themes/moonfly.toml"
]

[window]
dimensions = { columns = 140, lines = 35 }
opacity = 0.9
blur = true
startup_mode = "Maximized"
dynamic_title = true

[font]
normal = { family = "Iosevka Extended", style = "Regular" }

[cursor]
style = { shape = "Block", blinking = "On" }

[keyboard]
bindings = [
	{ key = "F11", mods = "Super", action = "ToggleFullscreen" },
	{ key = "F11", mods = "Super|Shift", action = "ToggleMaximized" }
]
